
server:
  port: 8080
  servlet:
    context-path: /

spring:
#  profiles:
#    active: local
  jpa: 
    hibernate.ddl-auto: update
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/demo
    url: jdbc:mysql://mysqldemo:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
    
      
jwt:
  header: Authorization
  base64-secret: dGhlcXVpY2ticm93bmZveGp1bXBzb3ZlcnRoZWxhenlkb2dqZHNha2xkamFza2RqYXNrbGRqc2pkbGtkc2FqZGxrc2pkbGtzYWpkbGtjY25uY25jc2tuYWQ4NzkzODQ3dzhkYXNka2FzZHVzaw==
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh
